Fix error: error: redefinition of 'struct rand_pool_info' struct rand_pool_info
 Changes to be committed:
	modified:   drivers/char/random.c
	modified:   include/linux/random.h

Change-Id: Ia7786b831ea024941b7dd0e29029852c0843fb7f